### ISSUE TITLE
simulate 4 traits at a time

### ISSUE THREAD

**Issue by ggittu** [precimed/simu#4]
Hello Oleksandr-

@ofrei I am trying to make use of this interesting simulation software. Trying to simulate 4 traits based on the rg b/w 4 of them. Will it be possible to work this out using this? Or are there any tweaks which can be done to make it happen ?

Hoping to hear from you.

Thank you,
George

**Comment by ofrei** [comment]
Hi George @ggittu 

I've done that using ``--causal-variants`` option which allows to specify a file that explicitly lists causal variants and their effect sizes. There is a small example of such file in the README.md.
You will need to write some python or R script to generate a list of rs#, and draw corresponding additive effects from multivariate normal distribution ( in Python that would be https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.multivariate_normal.html ) with covariance matrix that match  your genetic correlations. Then you save 4 .causal files with effect sizes for each of your traits, and run ``simu`` independently on each of these traits.

Further, there is another trick to simulate phenotypic correlation that are not driven by genetic correlations. You will then need to run ``simu`` with ``--hsq 1`` to pretend that your traits are 100% heritable (that's in addition to ``--causal-variants``). And once you have four 100% heritable phenorypes you can add a correlated noise ("environment") with desired covariance structure. It all boils down to ``y=G\beta+eps`` formula. Lately I've been using simu to computed ``G \beta`` (that's heavy lifting part with large G that doesn't even fit memory) - but generating ``beta`` and adding custom ``eps`` can be easily done in python or R.

Let me know if there is something else!

**Comment by ggittu** [comment]
Hi Oleksandr. @ofrei 

I really appreciate you in getting back. And this is really cool. Like you said first we generated a covariance matrix based on the genetic-correlation matrix we are interested in and heritability of 4 traits. After this based on the generated covariance matrix  we got the effects for a list of causal SNPS using numpy.random.multivariate_normal. And later we used these causal-variants to generate 4 trait phenotype values like you said. We have done linear regression on these traits to get the summary-stats and later verified with LDSC that it matches with what we have given, and these were obtained as expected. This was done as we are trying to get summary stats with the h2 and rg based on simulation 

One thing which I am trying to understand is, here we are passing the causal variants and their effects in to the ‘—causal-variants’ but  why simu is giving us output with another set of beta (BETA_c1)? Also here the causal variants remain the same for all the 4 traits we are simulating, but in real life scenario this wont be the case. So is there something we can do here so that there will be some causal SNPS being shared b/w the genetically correlated traits ?

Since we have decided to use this software for simulating traits in our study. We are trying to find the best possible approach using this software to simulate close to real life summary stats based on the rg and h2. 

Looking forward for your suggestions.

Thanks ,
George

**Comment by ofrei** [comment]
@ggittu great progress! Nice to know simu is working for you.

To your first question, BETA_c1 is different from the values you've put in ``--causal-variants`` file because ``simu`` re-normalize the phenotype to unit variance, i.e. ``Var(y)=1``.  In means that the underlying formula is ``y=alpha*(G beta+eps)`` , where ``alpha = 1/var(G beta + eps)``. When it comes to environmental noise, ``eps`` is a centered normal variable ``N(0, s2eps)`` , where variance ``s2eps`` is calculated from so that to ensure pre-defined heritability ``hsq = var(G beta) / var(G beta+eps) ``.

Also please note that even Var(beta)=1 (i.e. you've centered and scaled your beta's), and set ``--hsq 1`` (to remove ``eps``) then still the BETA_c1 column will be different, because what matters here is``Var(G beta)`` - not just ``Var(beta)``.

Also, note that there is an option ``--norm-effect`` which will change the way BETA_c1 is reported, as described in the readme file. But if you don't use ``--norm-effect`` than it's irrelevant.

**Comment by ofrei** [comment]
To your second question, you should put zeros as an effect size in ``--causal-variant`` file, e.g. like this:
```
file1.txt
rs1  0.01
rs2  0.03
rs3  0.00

#file2.txt
rs1  0.02
rs2  0.00
rs3  0.04
```
Here rs1 is shared,  rs2 is specific to trait1, and rs3 is specific to trait3.
In this case, however, the overall genetic correlation will be lower than covariance between shared effects.  This is along the lines that we've done in this paper: https://www.nature.com/articles/s41467-019-10310-0 

![image](https://user-images.githubusercontent.com/13171449/80733078-80cd5f00-8b0d-11ea-8267-d30fab00d081.png)

**Comment by ggittu** [comment]
Thanks Oleksandr @ofrei . This makes sense, and we will look at your paper to understand quite more on what you are mentioning.

I been checking at the summary stats file (we generated after doing linear regression on Simu generated trait values) to see the SNPs that are of significant( -log10(p_value)  > 5). But I was able to find only few SNP's from the .causals file generated by simu. In total there are 1277416 SNPS out of which 1277 of them are in .causal file. When I filtered for the SNPS’s with -log 10(p_value)  > 5 in summary stats there were only 60 SNPS from the 1277 causal SNP’s from the .causal file. I reduced the significance to SNP with -log 10(p_value ) > 4 but still there are only 100 of SNPS from the 1277 causal SNP’s from the .causal file. Why am I seeing this behavior ?

**Comment by ofrei** [comment]
What's your sample size? Most likely explanation is due to insufficient statistical power to detect an association.

**Comment by ggittu** [comment]
We have ~ 8000 samples. Is this considered to be good enough sample size ?

**Comment by ggittu** [comment]
@ofrei Or should we work it out on UK-Biobank size samples for more causals SNP's from the .causals to reach significance ? I must have tried it out , but our project dont have access to UK- Biobank. I see that your team have generated set of synthetic genotypes for 100K individuals and ca. 11M markers, will it be okay for you to share it? If so then I will work this out on that dataset, and I think its also better to do simulation on a bigger sample size. Currently I was using our own in-house dataset.

But I also want to point out that there are 518 SNP's with a significance of log 10(p_value ) > 5. But out of these 518 SNP's only 60 SNP's are from the ".causals" file. So its not that there are only 60 SNP's that have significance of log 10(p_value ) > 5, but rather there are only 60 SNPS from the causals. I was expecting a more number of the SNP's within the 518 SNP's coming from the causal SNP's

**Comment by ofrei** [comment]
Just for debugging I would try less causal variants (e.g. 10, or even 1). Then the average effect size per variant will be larger, thus more likely to reach statistical significance.
Other variants that you see reaching significance can be in LD (linkage disequilibrium) with your causals. They must belong to the same "spike" on a manhattan plot. Btw, did you make manhattan plots?  (e..g. using https://github.com/precimed/python_convert/blob/master/manhattan.py )

**Comment by ggittu** [comment]
Hi @ofrei   - I simulated it one more time, and out of the 1277 causal SNPS only 54 of them reached above significance of  log 10(p_value ) > 5 ( I am attaching Manhattan plot here, here the green dot in left Bottom is the SNP rs10157387 - its interesting that even if its causal how less significant it is) . 

<img width="1680" alt="Screen Shot 2020-05-01 at 3 16 05 AM" src="https://user-images.githubusercontent.com/13786610/80776358-1ee71680-8b5a-11ea-9c81-84f18529a7ea.png">

After this like you said I picked one SNP (rs10157387) from 1277 SNP's  and removed all the rest, and simulated traits using just SNP rs10157387 being causal. Like we expected its really significant that -log10(p) is of Inf. (attaching the other significant SNP's came with this). I checked to see if the other SNP's are in LD. Most of them are in high D' even if R2 of couple of them are quite low.

<img width="506" alt="Screen Shot 2020-05-01 at 3 10 01 AM" src="https://user-images.githubusercontent.com/13786610/80776381-2e665f80-8b5a-11ea-97ad-1756f8a1e01b.png">

So is the other causal SNP's not reaching the significance because sample size is of ~ 8000 ?

**Comment by ofrei** [comment]
Sounds reasonable! Yes, I think low sample size is the main reason. But overall I don't think it's possible to find all ~1277 causal variants even with UKB, so depending on your goals the 8000 might be sufficient. You could also increase h2 or reduce the number of causal variants as this increase average effect size per variant.

**Comment by ggittu** [comment]
@ofrei Thanks Oleksandr in looking at it. What could be the possible explanation why it's not possible to find ~1277 causal variants even with a bigger sample size, or is it that, at-least some proxy SNP's will be reported for all the 1277 causal SNPS ? 

And If I want to request for the set of synthetic genotypes for 100K individuals is there a formal request process that I should make ?

**Comment by ofrei** [comment]
@ggittu I would name "lack of statistical power" and "limitation of GWAS methodology" - due to LD and high polygenicity of complex human traits we don't expect to find 100% of the underlying genetic signal.
100k individuals - sorry, it's ~250 GB, I just don't have technical capacity to share so large dataset.
But we've used https://mathgen.stats.ox.ac.uk/genetics_software/hapgen/hapgen2.html to generate it, based on 1000 genomes EUR population. The only trick was to split 1000 genomes into ~4000 chunks, and for each chunk generate the entire 100K in one call to Hapgen2. I also suggest to pre-filter 1000 genomes - remove duplicated rs# and also keep MAF above 0.005.

**Comment by ofrei** [comment]
10K subjects can be downloaded here: https://1drv.ms/u/s!Ai1YZmdFa9atjIYnZkuTq3fCBFVF9Q?e=IYjcTK

**Comment by ggittu** [comment]
Thank you Oleksandr. Will work it out. Is it citing this GitHub or are there any paper on this simulation software that should be cited ?

**Comment by ofrei** [comment]
@ggittu Please site https://www.nature.com/articles/s41467-019-10310-0 . But good point, I should submit at least a biorxiv paper specificaly for simu tool.
